version: "3.2"
services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: service_name
      POSTGRES_DB: shopDB
      POSTGRES_PASSWORD: super_secret_pass
    ports:
      - "5757:5432"
    volumes:
      - ./.docker/database_scripts:/docker-entrypoint-initdb.d
    container_name: "resilient-postgre"
  redis:
    image: redis:4.0.8-alpine
    container_name: "resilient-redis"
    ports:
      - "6378:6379"
  products:
    image: resilient-service-products
    build:
      context: ./products-service
    ports:
      - "3103:3103"
    depends_on:
      - postgres
      - redis
    container_name: "resilient-service-products"
  shops:
    image: resilient-service-shops
    build:
      context: ./shops-service
    ports:
      - "3105:3105"
    depends_on:
      - postgres
      - redis
    container_name: "resilient-service-shops"
